development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://fyeopjspiodfjt:PmcPR00RNfyYcJ-4iB-Rts1owU@ec2-54-243-201-107.compute-1.amazonaws.com:5432/d9q090eqqaqfcs

# original version with redis
#production:
#  adapter: redis
#  url: redis://localhost:6379/1